### ISSUE TITLE
The requirements.txt file is not in correct format

### ISSUE THREAD

**Issue by kang2132** [nanlliu/Unsupervised-Compositional-Concepts-Discovery#1]
Dear authors,

It seems the requirements.txt file is not in correct format. When I run pip intstall -r requirements.txt it shows an error:

message: ERROR: Invalid requirement: '_libgcc_mutex=0.1=main' (from line 4 of requirements.txt)
Hint: = is not a valid operator. Did you mean == ?

Could you please provide a correct requirements file?

Thank you!

**Comment by HanLiii** [comment]
same issue

**Comment by joaquincabezas** [comment]
This format is not compatible with pip, it is for conda (therefore the issue is with the documentation). You can see in the same file the instructions are (per line 2):

`# $ conda create --name <env> --file <this file>`

The pypi_0 that you see at the end of the lines reflects that most packages were installed with pip inside the conda environment, and this can cause some trouble ([as per conda docs](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#pip-in-env)) if you want to reproduce the env in your computer.

Let me try to reproduce it and will come back later.

**Comment by joaquincabezas** [comment]
I used all the lines with pypi_0 to create a requirements.pip.txt file for install with pip. There are a few weird things, like CLIP with a 1.0 version, when currently latest is 0.2.0, and also composable-diffusion which is not on pypi (but you can install it with the [official repo](https://energy-based-model.github.io/Compositional-Visual-Generation-with-Composable-Diffusion-Models/) or by `pip install git+https://github.com/energy-based-model/Compositional-Visual-Generation-with-Composable-Diffusion-Models-PyTorch.git@dev`).

So after some manual work, I was able to execute the script, which runs through the initial steps but then when training starts sends a sigkill.

Hopefully the authors can share a proper requirements file soon. I will watch the repo for changes.

**Comment by joaquincabezas** [comment]
Ok I was able to run it (just in time for their poster tomorrow at [ICCV23](https://iccv2023.thecvf.com/)). The issue for the sigkill was that the GPU was not being used at all, so I manually set gpu_ids to _all_ in the accelerate_config.yaml.

So the steps are the following:

The file provided is a conda environment, but it is not going to work directly. Taking the lines which contain the string "pypi_0" I created a requirements.txt which can be installed in a new conda environment (you will need also to replace `=` with `==`). You will need to remove a few packages from that list:
- clip
- composable-diffusion
- torch
- torchaudio
- torchvision

Now you should remove the old requirements.txt file no to mess with the new one.

After creating the environment and activating it, please install the requirements.txt file that you have created with pip. After that go and install torch from the wheels (https://download.pytorch.org/whl/torch_stable.html). The selection for the wheels is (copying from the old requirements.txt):
    - torch==1.11.0+cu113
    - torchaudio==0.11.1+cu113
    - torchvision==0.12.0+cu113

You will need to download the files, then pip install "name.whl" i.e. `pip install "torchvision-0.13.1+cu113-cp38-cp38-linux_x86_64.whl"`

The reason is to stick as possible at the original configuration of the authors.

Then installed composable-diffusion with:
`pip install git+https://github.com/energy-based-model/Compositional-Visual-Generation-with-Composable-Diffusion-Models-PyTorch.git@dev`

The CLIP with:
```
pip install ftfy regex tqdm
pip install git+https://github.com/openai/CLIP.git
```

Now you will have the software installed and you can prepare the dataset for training. Take into account that the accelerate_config.yaml may need you manual entry of gpu_ids: all (at least that was my case).

Also, the parameters proposed in the instructions are maybe requiring a bit more GPU memory than available if you are using a A10G with 24Gb, please adjust them or use a bigger machine.

Hope it helps!

**Comment by nanlliu** [comment]
Hi,

I have updated the instructions. It should be working now.

**Comment by joaquincabezas** [comment]
I've tested the new instructions and worked perfectly, thanks!
